# Generated by Django 6.1 on 2026-08-20 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='scheduled', max_length=12)),
                ('symptoms', models.TextField(blank=True)),
                ('ai_urgency_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('ai_chief_complaint', models.CharField(blank=True, max_length=255)),
                ('ai_suggested_questions', models.JSONField(blank=True, default=list)),
                ('ai_pre_visit_raw', models.JSONField(blank=True, null=True)),
                ('ai_pre_visit_failed', models.BooleanField(default=False)),
                ('clinical_notes', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True, help_text="One line per medicine, e.g. 'Amoxicillin 500mg — 3x/day — 5 days'")),
                ('ai_post_visit_summary', models.TextField(blank=True)),
                ('ai_post_visit_failed', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to_set', to='appointments.appointment')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'date'], name='appointment_doctor__e7d63f_idx'), models.Index(fields=['patient', 'date'], name='appointment_patient_83aa7a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('doctor', 'date', 'start_time'), name='unique_scheduled_slot_per_doctor')],
            },
        ),
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'date', 'start_time'], name='appointment_doctor__147477_idx')],
            },
        ),
    ]
