# Generated by Django 6.1 on 2026-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='leave_conflict_pending',
            field=models.BooleanField(default=False, help_text='True if the doctor was marked on leave for this date after booking; patient needs to reschedule.'),
        ),
    ]
