# Generated by Django 6.1 on 2026-08-20 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('calendar', 'Google Calendar')], max_length=10)),
                ('notif_type', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('reminder', 'Appointment reminder'), ('medication_reminder', 'Medication reminder'), ('cancellation', 'Cancellation'), ('leave_conflict', 'Leave conflict notice'), ('post_visit_summary', 'Post-visit summary')], max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], max_length=10)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='appointments.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'notif_type'], name='notificatio_status_a76cde_idx')],
            },
        ),
    ]
